/* Copyright (c) Microsoft Corporation. All rights reserved.
   Licensed under the MIT License. */

// This file defines the mapping from the Avnet MT3620 Starter Kit (SK) to the
// 'template appliance' abstraction used by the templates.
// Some peripherals are on-board on the Avnet MT3620 SK, while other peripherals must be
// attached externally if needed.
// See https://aka.ms/AzureSphereHardwareDefinitions for more information on how to use
// hardware abstractions to enable apps to work across multiple hardware variants.

// This file is autogenerated from ../../joyitcar_appliance.json.  Do not edit it directly.

#pragma once
#include "avnet_mt3620_sk.h"

// MT3620 SK: I2C on Grove Connector.
#define I2C_MOTOR_DRIVER AVNET_MT3620_SK_ISU2_I2C

// MT3620 SK: User Button A.
#define USER_BUTTON_A AVNET_MT3620_SK_USER_BUTTON_A

// MT3620 SK: User Button B.
#define USER_BUTTON_B AVNET_MT3620_SK_USER_BUTTON_B

// MT3620 SK: User LED RED Channel.
#define RGBLED_RED AVNET_MT3620_SK_USER_LED_RED

// MT3620 SK: User LED GREEN Channel.
#define RGBLED_GREEN AVNET_MT3620_SK_USER_LED_GREEN

// MT3620 SK: User LED BLUE Channel.
#define RGBLED_BLUE AVNET_MT3620_SK_USER_LED_BLUE

// MT3620 SK: MikroBUS 1 UART Connector.
#define BLE4_UART_RXTX AVNET_MT3620_SK_ISU0_UART

// MT3620 SK:  MikroBUS 1 UART RST Channel.
#define BLE4_UART_RST AVNET_MT3620_SK_GPIO16

// MT3620 SK: MikroBUS 1 UART CS Channel.
#define BLE4_UART_CTS AVNET_MT3620_SK_GPIO34

// MT3620 SK: MikroBUS 1 UART PWM Channel.
#define BLE4_UART_DSR AVNET_MT3620_SK_GPIO0

// MT3620 SK: MikroBUS 1 UART AN Channel.
#define BLE4_UART_DTR AVNET_MT3620_SK_GPIO42

// MT3620 SK: MikroBUS 1 UART INT Channel.
#define BLE4_UART_RTS AVNET_MT3620_SK_GPIO2

